### ISSUE TITLE
Add the option to use `latest` in `since-perl`

### ISSUE THREAD

**Issue by atoomic** [perl-actions/perl-versions#4]
The goal would be to be able to use the `latest` current Perl version (with or without `devel`)
This could be used a in few workflow like the one from https://github.com/abw/Template2

Idea:

```yaml
  perl-versions:
    runs-on: ubuntu-latest
    name: List Perl versions
    outputs:
      perl-versions: ${{ steps.action.outputs.perl-versions }}
    steps:
      - id: action
        uses: perl-actions/perl-versions@v1
        with:
          since-perl: latest
          with-devel: true
```
